// Generated by tools/build-demo-profile.mjs. Do not edit by hand.
export const PROFILE_META = Object.freeze({
  "spec_version": "0.4.0",
  "profile_id": "sia-minimal",
  "profile_version": "0.4.0",
  "catalog_version": "0.4.0",
  "catalog_sha256": "1ec08113e44f7c818bd9d70b20b35c52cc7284d846cff43eb179ddc26ed64e23"
});

export const ACTOR_CLASS_IDS = Object.freeze([
  "human_direct",
  "adas",
  "service",
  "third_party_app",
  "agent_local",
  "agent_cloud"
]);

export const CONTEXT_AXES = Object.freeze([
  "motion_state",
  "operating_mode",
  "energy_state",
  "road_type",
  "driver_state",
  "occupancy"
]);

export const CONTEXT_POLICY = Object.freeze({
  "spec_version": "0.4.0",
  "policy_id": "sia:policy:core-context:1",
  "policy_version": "0.4.0",
  "axis_requirements": {
    "motion_state": {
      "max_age_ms": 100,
      "min_confidence": 95,
      "unknown_handling": "safe_worst_case"
    },
    "operating_mode": {
      "max_age_ms": 500,
      "min_confidence": 90,
      "unknown_handling": "safe_worst_case"
    },
    "energy_state": {
      "max_age_ms": 1000,
      "min_confidence": 90,
      "unknown_handling": "safe_worst_case"
    },
    "road_type": {
      "max_age_ms": 300000,
      "min_confidence": 50,
      "unknown_handling": "safe_worst_case"
    },
    "driver_state": {
      "max_age_ms": 250,
      "min_confidence": 70,
      "unknown_handling": "safe_worst_case"
    },
    "occupancy": {
      "max_age_ms": 1000,
      "min_confidence": 80,
      "unknown_handling": "fail_closed"
    }
  },
  "attention_modifiers": {
    "road_type": {
      "urban": 1,
      "rural": 0.9,
      "highway": 1.2,
      "off_road": 1.3,
      "unknown": 1.3
    },
    "driver_state": {
      "attentive": 1,
      "drowsy": 1.3,
      "distracted": 1.5,
      "not_monitoring": 1.5,
      "unknown": 1.5
    }
  },
  "integrity": {
    "issuer": "SIA Test Policy Authority",
    "key_id": "vehicle-hsm:policy:1",
    "algorithm": "EdDSA",
    "signature": "YM2UNreco4-9TUcnDPc60KoXTJ_Y9bSWg0TKEtOVC6mcuR5Xtng_b22EAfVte1HgebKCSWevW8BemOp-w7FRBA"
  }
});

export const NODE_RECORDS = Object.freeze([
  {
    "declaration": {
      "id": "Interaction.Event.Alert.Collision.Warning",
      "inherits_from": "Interaction.Event.Alert",
      "since_version": "0.4.0",
      "direction": "system_to_occupant",
      "target_role": "driver",
      "temporal_type": "discrete",
      "priority": "critical",
      "interruptibility": "non_interruptible",
      "semantic_validity_ms": 500,
      "payload_schema_ref": "sia:payload:collision-warning:1",
      "payload_schema_sha256": "938adfbbd73a2e0b714882a0af012319c8d7eddb9cb1fe5c8511fb39d7a7159a",
      "trust_requirements": {
        "signed_origin_required": true,
        "permitted_actor_classes": [
          "adas"
        ],
        "max_ingress_age_ms": 200,
        "replay_protection": "required",
        "session_revocation_required": true
      },
      "attention_metrics": {
        "glance_time_estimated_ms": 800,
        "mean_single_glance_ms": 300,
        "task_steps": 0,
        "voice_alt_available": true,
        "cognitive_load": "minimal"
      },
      "context_policy": {
        "policy_ref": "sia:policy:core-context:1",
        "policy_sha256": "b614a38045ea31e2abd6b82ef88b43b158b54aa30078b90bf78708cfeb798e22",
        "applicability": "always",
        "unknown_context": "safe_worst_case",
        "on_blocked": {
          "disposition": "never_block"
        }
      },
      "presentation_contract": {
        "preferred_renderers": [
          "cluster",
          "voice"
        ],
        "required_renderers": [],
        "delivery_success_policy": "any_selected_presented",
        "delivery_timeout_ms": 300,
        "degradation_policy": "next_eligible"
      },
      "occupant_response": {
        "kind": "explicit_or_timeout",
        "authority": "driver_only",
        "timeout_ms": 2000
      },
      "pii_class": "none",
      "accessibility_alternatives": [
        "visual",
        "auditory"
      ],
      "regulatory_basis": [
        "ISO_15623",
        "UNECE_R152"
      ]
    },
    "declaration_sha256": "533e5863cdcd2f9d2767bca3a4dbc4e903af7bd5fa076d9a11710d430008e658"
  },
  {
    "declaration": {
      "id": "Interaction.Event.Alert.Lane.Departure.Warning",
      "inherits_from": "Interaction.Event.Alert",
      "since_version": "0.4.0",
      "direction": "system_to_occupant",
      "target_role": "driver",
      "temporal_type": "discrete",
      "priority": "high",
      "interruptibility": "non_interruptible",
      "semantic_validity_ms": 1000,
      "payload_schema_ref": "sia:payload:lane-departure-warning:1",
      "payload_schema_sha256": "7642a6ede8d81146c35f5ade8725b11c3574d1bd0ee6a06d86d7cea3ff361ef6",
      "trust_requirements": {
        "signed_origin_required": true,
        "permitted_actor_classes": [
          "adas"
        ],
        "max_ingress_age_ms": 300,
        "replay_protection": "required",
        "session_revocation_required": true
      },
      "attention_metrics": {
        "glance_time_estimated_ms": 600,
        "mean_single_glance_ms": 250,
        "task_steps": 0,
        "voice_alt_available": true,
        "cognitive_load": "minimal"
      },
      "context_policy": {
        "policy_ref": "sia:policy:core-context:1",
        "policy_sha256": "b614a38045ea31e2abd6b82ef88b43b158b54aa30078b90bf78708cfeb798e22",
        "applicability": "moving_only",
        "unknown_context": "safe_worst_case",
        "on_blocked": {
          "disposition": "never_block"
        }
      },
      "presentation_contract": {
        "preferred_renderers": [
          "cluster",
          "voice"
        ],
        "required_renderers": [],
        "delivery_success_policy": "any_selected_presented",
        "delivery_timeout_ms": 400,
        "degradation_policy": "next_eligible"
      },
      "occupant_response": {
        "kind": "none"
      },
      "pii_class": "none",
      "accessibility_alternatives": [
        "visual",
        "auditory"
      ],
      "regulatory_basis": [
        "UNECE_R79"
      ]
    },
    "declaration_sha256": "4cb40e3c17c81533f68d2384adf513dda236faba75608d4447c119b0164cdaf2"
  },
  {
    "declaration": {
      "id": "Interaction.Event.Notification.Diagnostic.CollisionSensorTest",
      "inherits_from": "Interaction.Event.Notification",
      "since_version": "0.4.0",
      "direction": "system_to_occupant",
      "target_role": "driver",
      "temporal_type": "discrete",
      "priority": "normal",
      "interruptibility": "deferable",
      "semantic_validity_ms": 60000,
      "payload_schema_ref": "sia:payload:collision-sensor-test:1",
      "payload_schema_sha256": "15f79bf848082f18963b6e70dbf122be8027aeb372aecd4d328914c2cd20ad19",
      "trust_requirements": {
        "signed_origin_required": true,
        "permitted_actor_classes": [
          "adas",
          "service"
        ],
        "max_ingress_age_ms": 5000,
        "replay_protection": "required",
        "session_revocation_required": true
      },
      "attention_metrics": {
        "glance_time_estimated_ms": 1200,
        "mean_single_glance_ms": 500,
        "task_steps": 2,
        "voice_alt_available": false,
        "cognitive_load": "moderate"
      },
      "context_policy": {
        "policy_ref": "sia:policy:core-context:1",
        "policy_sha256": "b614a38045ea31e2abd6b82ef88b43b158b54aa30078b90bf78708cfeb798e22",
        "applicability": "always",
        "unknown_context": "safe_worst_case",
        "on_blocked": {
          "disposition": "defer",
          "ttl_ms": 60000,
          "reevaluate_on": [
            "driver_state_change",
            "motion_state_change",
            "operating_mode_change"
          ],
          "on_expiry": "drop",
          "max_pending": 10
        }
      },
      "presentation_contract": {
        "preferred_renderers": [
          "ivi"
        ],
        "required_renderers": [],
        "delivery_success_policy": "primary_presented",
        "delivery_timeout_ms": 1200,
        "degradation_policy": "no_degradation"
      },
      "occupant_response": {
        "kind": "none"
      },
      "pii_class": "none",
      "accessibility_alternatives": [
        "visual"
      ]
    },
    "declaration_sha256": "cb09b1c039a2f8bb2fa9f390a04158e6c4772eecd06d4b30b4f7682a68a1ecec"
  },
  {
    "declaration": {
      "id": "Interaction.Event.Notification.Media.NowPlaying",
      "inherits_from": "Interaction.Event.Notification",
      "since_version": "0.4.0",
      "direction": "system_to_occupant",
      "target_role": "any_occupant",
      "temporal_type": "discrete",
      "priority": "low",
      "interruptibility": "deferable",
      "semantic_validity_ms": 30000,
      "payload_schema_ref": "sia:payload:now-playing:1",
      "payload_schema_sha256": "bffee801a20ea273d59b0a62e894619a6292cf4c84d67ccaa49ab9acf52609f0",
      "trust_requirements": {
        "signed_origin_required": true,
        "permitted_actor_classes": [
          "service",
          "third_party_app"
        ],
        "max_ingress_age_ms": 5000,
        "replay_protection": "required",
        "session_revocation_required": true
      },
      "attention_metrics": {
        "glance_time_estimated_ms": 1500,
        "mean_single_glance_ms": 450,
        "task_steps": 1,
        "voice_alt_available": true,
        "cognitive_load": "minimal"
      },
      "context_policy": {
        "policy_ref": "sia:policy:core-context:1",
        "policy_sha256": "b614a38045ea31e2abd6b82ef88b43b158b54aa30078b90bf78708cfeb798e22",
        "applicability": "always",
        "unknown_context": "safe_worst_case",
        "on_blocked": {
          "disposition": "coalesce",
          "ttl_ms": 30000,
          "coalescing_key_fields": [
            "node_id",
            "target_role",
            "actor_id",
            "payload.session_id"
          ],
          "reevaluate_on": [
            "driver_state_change",
            "motion_state_change",
            "operating_mode_change"
          ],
          "on_expiry": "drop",
          "max_pending_per_key": 1
        }
      },
      "presentation_contract": {
        "preferred_renderers": [
          "ivi",
          "voice"
        ],
        "required_renderers": [],
        "delivery_success_policy": "any_selected_presented",
        "delivery_timeout_ms": 1200,
        "degradation_policy": "next_eligible"
      },
      "occupant_response": {
        "kind": "none"
      },
      "pii_class": "personal",
      "accessibility_alternatives": [
        "visual",
        "auditory"
      ]
    },
    "declaration_sha256": "43109dc5336099b762f420ca5e8c3139d0bdf4d3c57ef51e858129d4389919d2"
  },
  {
    "declaration": {
      "id": "Interaction.Event.Notification.Assistant.Suggestion",
      "inherits_from": "Interaction.Event.Notification",
      "since_version": "0.4.0",
      "direction": "system_to_occupant",
      "target_role": "driver",
      "temporal_type": "discrete",
      "priority": "low",
      "interruptibility": "deferable",
      "semantic_validity_ms": 5000,
      "payload_schema_ref": "sia:payload:assistant-suggestion:1",
      "payload_schema_sha256": "01f74f8d1b63737f7aa1a04f90c3f893c984e470bad30252acdc12ed3dcac17c",
      "trust_requirements": {
        "signed_origin_required": true,
        "permitted_actor_classes": [
          "agent_local",
          "agent_cloud",
          "service"
        ],
        "max_ingress_age_ms": 2000,
        "replay_protection": "required",
        "session_revocation_required": true
      },
      "attention_metrics": {
        "glance_time_estimated_ms": 1000,
        "mean_single_glance_ms": 400,
        "task_steps": 1,
        "voice_alt_available": true,
        "cognitive_load": "minimal"
      },
      "context_policy": {
        "policy_ref": "sia:policy:core-context:1",
        "policy_sha256": "b614a38045ea31e2abd6b82ef88b43b158b54aa30078b90bf78708cfeb798e22",
        "applicability": "always",
        "unknown_context": "safe_worst_case",
        "on_blocked": {
          "disposition": "drop",
          "audit_required": true
        }
      },
      "presentation_contract": {
        "preferred_renderers": [
          "ivi",
          "voice"
        ],
        "required_renderers": [],
        "delivery_success_policy": "any_selected_presented",
        "delivery_timeout_ms": 1200,
        "degradation_policy": "drop_with_audit"
      },
      "occupant_response": {
        "kind": "none"
      },
      "pii_class": "personal",
      "accessibility_alternatives": [
        "visual",
        "auditory"
      ]
    },
    "declaration_sha256": "092938b6c896caecb3424731205e84b25c99805c559011eae864e356bfcf43cc"
  }
]);

export const RENDERER_DECLARATIONS = Object.freeze([
  {
    "renderer_id": "Renderer.Cluster.Primary",
    "kind": "cluster",
    "capability_version": "0.4.0",
    "safety_assurance": {
      "level": "safety_relevant",
      "evidence_ref": "urn:oem:assurance:cluster-primary:2026-07"
    },
    "capabilities": {
      "max_simultaneous_elements": 6,
      "text_max_chars": 48,
      "max_glance_budget_ms": 1000,
      "supports_animation": true,
      "glance_optimized": true
    },
    "attestation": {
      "issuer": "OEM.RendererRegistry",
      "key_id": "vehicle-hsm:renderer-registry:2",
      "algorithm": "ES256",
      "signature": "luQlf7lZ1DMtTAJ1If4kx6pnxVhKMUKgBvjfBlFajh8mdT67lG97Tc9d5GFQBlbX2EyTVcZG9CLYvjO3-O62aw"
    }
  },
  {
    "renderer_id": "Renderer.IVI.Primary",
    "kind": "ivi",
    "capability_version": "0.4.0",
    "safety_assurance": {
      "level": "general",
      "evidence_ref": null
    },
    "capabilities": {
      "max_simultaneous_elements": 12,
      "text_max_chars": 160,
      "max_glance_budget_ms": 2200,
      "supports_animation": true,
      "glance_optimized": false
    },
    "attestation": {
      "issuer": "OEM.RendererRegistry",
      "key_id": "vehicle-hsm:renderer-registry:2",
      "algorithm": "ES256",
      "signature": "rxCY38_zOnugpiMWpRCRmzQpe-bFAz-BLptAEVTvrj8JEzcm02RBt1aSsdYN-_3LgZxXIYU2udz3x1U1sJ6xdw"
    }
  },
  {
    "renderer_id": "Renderer.Voice.Primary",
    "kind": "voice",
    "capability_version": "0.4.0",
    "safety_assurance": {
      "level": "safety_relevant",
      "evidence_ref": "urn:oem:assurance:voice-primary:2026-07"
    },
    "capabilities": {
      "max_simultaneous_elements": 1,
      "text_max_chars": null,
      "max_glance_budget_ms": null,
      "supports_animation": false,
      "glance_optimized": true
    },
    "attestation": {
      "issuer": "OEM.RendererRegistry",
      "key_id": "vehicle-hsm:renderer-registry:2",
      "algorithm": "ES256",
      "signature": "4SvidkfXtWHPP8ALyC2ZAUsbKOxLIv5Ujs3k5WCm22Xp2NjhneSMOWj8cHHypxcQrO2diD6OOvgNA-mM49whbw"
    }
  }
]);

export const DOC_EXCERPTS = Object.freeze({
  "catalog": {
    "spec_version": "0.4.0",
    "profile_id": "sia-minimal",
    "profile_version": "0.4.0",
    "catalog_version": "0.4.0",
    "generated_at_ms": 1784116800000,
    "nodes": [
      {
        "id": "Interaction.Event.Alert.Collision.Warning",
        "priority": "critical"
      },
      {
        "id": "Interaction.Event.Alert.Lane.Departure.Warning",
        "priority": "high"
      },
      {
        "id": "Interaction.Event.Notification.Diagnostic.CollisionSensorTest",
        "priority": "normal"
      },
      {
        "id": "Interaction.Event.Notification.Media.NowPlaying",
        "priority": "low"
      },
      {
        "id": "Interaction.Event.Notification.Assistant.Suggestion",
        "priority": "low"
      }
    ],
    "integrity": {
      "issuer": "SIA Test Catalog Authority",
      "key_id": "vehicle-hsm:catalog:1",
      "algorithm": "EdDSA"
    }
  },
  "registry": {
    "spec_version": "0.4.0",
    "profile_id": "sia-minimal",
    "registry_version": "0.4.0",
    "credentials": [
      {
        "credential_id": "11111111-1111-4111-8111-111111111111",
        "actor_id": "ADAS_v2.3.1",
        "actor_class": "adas",
        "key_id": "vehicle-hsm:adas:7",
        "valid_from_ms": 1700000000000,
        "valid_until_ms": 1900000000000,
        "status": "active"
      }
    ],
    "integrity": {
      "issuer": "SIA Test Actor Authority",
      "key_id": "vehicle-hsm:actor-registry:1",
      "algorithm": "EdDSA"
    }
  },
  "policy": {
    "spec_version": "0.4.0",
    "policy_id": "sia:policy:core-context:1",
    "policy_version": "0.4.0",
    "axis_requirements": {
      "motion_state": {
        "max_age_ms": 100,
        "min_confidence": 95,
        "unknown_handling": "safe_worst_case"
      },
      "operating_mode": {
        "max_age_ms": 500,
        "min_confidence": 90,
        "unknown_handling": "safe_worst_case"
      },
      "energy_state": {
        "max_age_ms": 1000,
        "min_confidence": 90,
        "unknown_handling": "safe_worst_case"
      },
      "road_type": {
        "max_age_ms": 300000,
        "min_confidence": 50,
        "unknown_handling": "safe_worst_case"
      },
      "driver_state": {
        "max_age_ms": 250,
        "min_confidence": 70,
        "unknown_handling": "safe_worst_case"
      },
      "occupancy": {
        "max_age_ms": 1000,
        "min_confidence": 80,
        "unknown_handling": "fail_closed"
      }
    },
    "attention_modifiers": {
      "road_type": {
        "urban": 1,
        "rural": 0.9,
        "highway": 1.2,
        "off_road": 1.3,
        "unknown": 1.3
      },
      "driver_state": {
        "attentive": 1,
        "drowsy": 1.3,
        "distracted": 1.5,
        "not_monitoring": 1.5,
        "unknown": 1.5
      }
    },
    "integrity": {
      "issuer": "SIA Test Policy Authority",
      "key_id": "vehicle-hsm:policy:1",
      "algorithm": "EdDSA"
    }
  },
  "node": {
    "id": "Interaction.Event.Alert.Collision.Warning",
    "inherits_from": "Interaction.Event.Alert",
    "since_version": "0.4.0",
    "direction": "system_to_occupant",
    "target_role": "driver",
    "temporal_type": "discrete",
    "priority": "critical",
    "interruptibility": "non_interruptible",
    "semantic_validity_ms": 500,
    "payload_schema_ref": "sia:payload:collision-warning:1",
    "payload_schema_sha256": "938adfbbd73a2e0b714882a0af012319c8d7eddb9cb1fe5c8511fb39d7a7159a",
    "trust_requirements": {
      "signed_origin_required": true,
      "permitted_actor_classes": [
        "adas"
      ],
      "max_ingress_age_ms": 200,
      "replay_protection": "required",
      "session_revocation_required": true
    },
    "attention_metrics": {
      "glance_time_estimated_ms": 800,
      "mean_single_glance_ms": 300,
      "task_steps": 0,
      "voice_alt_available": true,
      "cognitive_load": "minimal"
    },
    "context_policy": {
      "policy_ref": "sia:policy:core-context:1",
      "policy_sha256": "b614a38045ea31e2abd6b82ef88b43b158b54aa30078b90bf78708cfeb798e22",
      "applicability": "always",
      "unknown_context": "safe_worst_case",
      "on_blocked": {
        "disposition": "never_block"
      }
    },
    "presentation_contract": {
      "preferred_renderers": [
        "cluster",
        "voice"
      ],
      "required_renderers": [],
      "delivery_success_policy": "any_selected_presented",
      "delivery_timeout_ms": 300,
      "degradation_policy": "next_eligible"
    },
    "occupant_response": {
      "kind": "explicit_or_timeout",
      "authority": "driver_only",
      "timeout_ms": 2000
    },
    "pii_class": "none",
    "accessibility_alternatives": [
      "visual",
      "auditory"
    ],
    "regulatory_basis": [
      "ISO_15623",
      "UNECE_R152"
    ]
  },
  "instance": {
    "spec_version": "0.4.0",
    "profile_id": "sia-minimal",
    "profile_version": "0.4.0",
    "catalog_version": "0.4.0",
    "catalog_sha256": "1ec08113e44f7c818bd9d70b20b35c52cc7284d846cff43eb179ddc26ed64e23",
    "node_id": "Interaction.Event.Alert.Collision.Warning",
    "node_schema_sha256": "533e5863cdcd2f9d2767bca3a4dbc4e903af7bd5fa076d9a11710d430008e658",
    "instance_id": "c8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b21",
    "occurred_at_ms": 1784116800000,
    "valid_until_ms": 1784116800500,
    "target_role": "driver",
    "payload": {
      "time_to_collision_s": 1.4,
      "threat_bearing_deg": 12,
      "threat_range_m": 18,
      "relative_speed_kmh": 42
    },
    "attestation": {
      "actor_class": "adas",
      "actor_id": "ADAS_v2.3.1",
      "actor_registry_version": "0.4.0",
      "actor_registry_sha256": "6917bf5dbd4a06eeab25f4541207a2413420438c5977f831bbb1cbf870137413",
      "actor_credential_id": "11111111-1111-4111-8111-111111111111",
      "actor_credential_sha256": "a0cf9a2463d1a22c50e9eb916dfc96f26d607998ffe1cf8337d8548096362b1a",
      "key_id": "vehicle-hsm:adas:7",
      "algorithm": "ES256",
      "timestamp_ms": 1784116800000,
      "nonce": "cmFuZG9tLW5vbmNlLTE",
      "provenance_chain": [
        "ADAS_v2.3.1"
      ]
    }
  },
  "context": {
    "context_id": "1a2b3c4d-1111-4aaa-8bbb-1234567890ab",
    "captured_at_ms": 1784116800040,
    "policy_ref": "sia:policy:core-context:1",
    "policy_version": "0.4.0",
    "policy_sha256": "b614a38045ea31e2abd6b82ef88b43b158b54aa30078b90bf78708cfeb798e22",
    "axes": {
      "motion_state": {
        "value": "moving",
        "source_id": "Vehicle.SpeedState",
        "observed_at_ms": 1784116800036,
        "confidence": 100
      },
      "operating_mode": {
        "value": "driving",
        "source_id": "Vehicle.OperatingMode",
        "observed_at_ms": 1784116800036,
        "confidence": 100
      },
      "energy_state": {
        "value": "not_charging",
        "source_id": "Vehicle.ChargeState",
        "observed_at_ms": 1784116800030,
        "confidence": 100
      },
      "road_type": {
        "value": "highway",
        "source_id": "Navigation.RoadClass",
        "observed_at_ms": 1784116799800,
        "confidence": 96
      },
      "driver_state": {
        "value": "attentive",
        "source_id": "DMS.AttentionState",
        "observed_at_ms": 1784116800028,
        "confidence": 92
      },
      "occupancy": {
        "occupied_roles": [
          "driver"
        ],
        "source_id": "Cabin.Occupancy",
        "observed_at_ms": 1784116800030,
        "confidence": 98
      }
    },
    "integrity": {
      "issuer": "Vehicle Context Authority",
      "key_id": "vehicle-hsm:context:3",
      "algorithm": "EdDSA"
    }
  },
  "renderer": {
    "renderer_id": "Renderer.Cluster.Primary",
    "kind": "cluster",
    "capability_version": "0.4.0",
    "safety_assurance": {
      "level": "safety_relevant",
      "evidence_ref": "urn:oem:assurance:cluster-primary:2026-07"
    },
    "capabilities": {
      "max_simultaneous_elements": 6,
      "text_max_chars": 48,
      "max_glance_budget_ms": 1000,
      "supports_animation": true,
      "glance_optimized": true
    },
    "attestation": {
      "issuer": "OEM.RendererRegistry",
      "key_id": "vehicle-hsm:renderer-registry:2",
      "algorithm": "ES256"
    }
  },
  "retention": {
    "retention_id": "a8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b25",
    "spec_version": "0.4.0",
    "profile_version": "0.4.0",
    "catalog_version": "0.4.0",
    "catalog_sha256": "1ec08113e44f7c818bd9d70b20b35c52cc7284d846cff43eb179ddc26ed64e23",
    "instance_id": "b8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b26",
    "context_id": "2a2b3c4d-1111-4aaa-8bbb-1234567890ac",
    "node_id": "Interaction.Event.Notification.Media.NowPlaying",
    "node_schema_sha256": "43109dc5336099b762f420ca5e8c3139d0bdf4d3c57ef51e858129d4389919d2",
    "policy_ref": "sia:policy:core-context:1",
    "policy_sha256": "b614a38045ea31e2abd6b82ef88b43b158b54aa30078b90bf78708cfeb798e22",
    "disposition": "coalesce",
    "state": "held",
    "retained_at_ms": 1784116800100,
    "expires_at_ms": 1784116830000,
    "valid_until_ms": 1784116830000,
    "coalescing_key_sha256": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    "reevaluate_on": [
      "driver_state_change",
      "motion_state_change",
      "operating_mode_change"
    ],
    "policy_version": "0.4.0",
    "reason_code": "CONTEXT_COALESCED_DISTRACTED"
  },
  "plan": {
    "decision_id": "d8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b22",
    "instance_id": "c8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b21",
    "context_id": "1a2b3c4d-1111-4aaa-8bbb-1234567890ab",
    "spec_version": "0.4.0",
    "profile_version": "0.4.0",
    "catalog_version": "0.4.0",
    "catalog_sha256": "1ec08113e44f7c818bd9d70b20b35c52cc7284d846cff43eb179ddc26ed64e23",
    "node_schema_sha256": "533e5863cdcd2f9d2767bca3a4dbc4e903af7bd5fa076d9a11710d430008e658",
    "policy_ref": "sia:policy:core-context:1",
    "policy_version": "0.4.0",
    "policy_sha256": "b614a38045ea31e2abd6b82ef88b43b158b54aa30078b90bf78708cfeb798e22",
    "created_at_ms": 1784116800060,
    "selected": [
      {
        "renderer_id": "Renderer.Cluster.Primary",
        "role": "primary"
      },
      {
        "renderer_id": "Renderer.Voice.Primary",
        "role": "fallback"
      }
    ],
    "rejected": [
      {
        "renderer_id": "Renderer.IVI.Primary",
        "reason_code": "SAFETY_PROFILE_INELIGIBLE"
      }
    ],
    "delivery_success_policy": "any_selected_presented",
    "delivery_timeout_ms": 300,
    "reason_code": "PRIMARY_WITH_FALLBACK_STANDBY"
  },
  "dispatch": {
    "attempt_id": "a0e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b20",
    "decision_id": "d8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b22",
    "instance_id": "c8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b21",
    "renderer_id": "Renderer.Cluster.Primary",
    "role": "primary",
    "sequence": 0,
    "previous_attempt_id": null,
    "dispatched_at_ms": 1784116800060,
    "deadline_at_ms": 1784116800360,
    "state": "dispatched",
    "reason_code": null,
    "integrity": {
      "issuer": "coordination_runtime",
      "key_id": "vehicle-hsm:runtime:1",
      "algorithm": "EdDSA"
    }
  },
  "receipt": {
    "receipt_id": "e8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b23",
    "attempt_id": "a0e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b20",
    "receipt_sequence": 0,
    "decision_id": "d8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b22",
    "instance_id": "c8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b21",
    "renderer_id": "Renderer.Cluster.Primary",
    "issuer": "renderer",
    "state": "presented",
    "observed_at_ms": 1784116800132,
    "elapsed_ms": 72,
    "reason_code": null,
    "attestation": {
      "key_id": "vehicle-hsm:cluster:4",
      "algorithm": "HMAC-SHA-256"
    }
  },
  "response": {
    "response_id": "f8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b24",
    "decision_id": "d8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b22",
    "instance_id": "c8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b21",
    "context_id": "1a2b3c4d-1111-4aaa-8bbb-1234567890ab",
    "delivery_receipt_ids": [
      "e8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b23"
    ],
    "state": "acknowledged",
    "authority": "driver_only",
    "subject_role": "driver",
    "opened_at_ms": 1784116800132,
    "deadline_at_ms": 1784116802132,
    "occurred_at_ms": 1784116800552,
    "input_channel": "InputDevice.SteeringWheel.Right.Press",
    "evidence": {
      "kind": "verified_input",
      "key_id": "vehicle-hsm:input:5",
      "algorithm": "HMAC-SHA-256"
    }
  },
  "audit": {
    "event_id": "98e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b27",
    "sequence": 0,
    "previous_record_sha256": null,
    "record_sha256": "af85e5d61a4f1a2470ec607e0b201bbcd8ffbfd5eed07213cf3e1b9e058dca33",
    "timestamp_ms": 1784116800132,
    "instance_id": "c8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b21",
    "node_schema_sha256": "533e5863cdcd2f9d2767bca3a4dbc4e903af7bd5fa076d9a11710d430008e658",
    "catalog_sha256": "1ec08113e44f7c818bd9d70b20b35c52cc7284d846cff43eb179ddc26ed64e23",
    "context_id": "1a2b3c4d-1111-4aaa-8bbb-1234567890ab",
    "phase": "delivery",
    "outcome_code": "DELIVERY_PRESENTED",
    "spec_version": "0.4.0",
    "profile_version": "0.4.0",
    "catalog_version": "0.4.0",
    "policy_version": "0.4.0",
    "policy_ref": "sia:policy:core-context:1",
    "policy_sha256": "b614a38045ea31e2abd6b82ef88b43b158b54aa30078b90bf78708cfeb798e22",
    "details": {
      "renderer_id": "Renderer.Cluster.Primary",
      "receipt_id": "e8e1f4b2-7bd0-4c44-9a8e-0a9c7c2c4b23"
    }
  }
});
