name: Markdown checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            *.md
            **/*.md
